"use strict";

/*
  SSC Smart Study — stable app engine
  Mock Test UI is isolated from the rest of the navigation/content system.
  Data-driven: any folder containing mock-test.json gets the same engine.
*/

const APP={dataFolder:"data",currentPage:"",params:{},state:{category:null,path:[]},mock:{data:null,index:0,selected:{},timer:null,timeLeft:0}};
const $=(s,r=document)=>r.querySelector(s);
const $$=(s,r=document)=>Array.from(r.querySelectorAll(s));
function escapeHTML(v=""){return String(v).replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#39;");}
function sanitizeSegment(v=""){return String(v||"").trim().replace(/[\\/]+/g,"").replace(/\s+/g," ");}
function joinPath(...parts){return parts.flat().map(sanitizeSegment).filter(Boolean).join("/");}
function splitPath(v=""){return String(v||"").split("/").map(sanitizeSegment).filter(Boolean);}
function dataPath(...parts){return [APP.dataFolder,...parts].filter(Boolean).join("/");}
function getParams(){const u=new URL(location.href);return Object.fromEntries(u.searchParams.entries());}
function getPageName(){return location.pathname.split("/").pop()||"index.html";}
function formatTitle(v){return String(v||"").replaceAll("-"," ").replace(/\b\w/g,m=>m.toUpperCase());}
function getCurrentPathSegments(){const p=splitPath(APP.params.path||"");return p.length?p:[APP.params.subject,APP.params.chapter,APP.params.topic].map(sanitizeSegment).filter(Boolean);}
function currentDirTitle(category,segments){return segments?.length?formatTitle(segments[segments.length-1]):formatTitle(category);}
function currentDirPath(category,segments=[]){return dataPath(category,...segments);}
function itemLabel(item,fallback="Item"){return item.title||item.name||item.label||fallback;}
function jsParams(p){return JSON.stringify(p);}
function breadcrumbsHTML(category,segments=[]){const crumbs=[{label:formatTitle(category),params:{category}}];const acc=[];for(const seg of segments){acc.push(seg);crumbs.push({label:formatTitle(seg),params:{category,path:joinPath(acc)}})}return `<div class="breadcrumbs">${crumbs.map((c,i)=>`${i?'<span class="crumb-sep">/</span>':''}<button class="crumb-btn" onclick='goTo("study.html",${jsParams(c.params)})'>${escapeHTML(c.label)}</button>`).join("")}</div>`}

function injectUIStyles(){if($("#ui-enhancements-style"))return;const s=document.createElement("style");s.id="ui-enhancements-style";s.textContent=`
#app{transition:opacity .22s ease,transform .22s ease}.app-fade{opacity:0;transform:translateY(6px)}.app-fade-in{opacity:1;transform:translateY(0)}
.card,.question-box,.list-item{animation:uiFade .3s ease both}@keyframes uiFade{from{opacity:0;transform:translateY(8px)}to{opacity:1;transform:none}}
.category-card,.leaf-card{cursor:pointer;user-select:none;-webkit-tap-highlight-color:transparent}.category-card:focus-visible,.leaf-card:focus-visible{outline:3px solid var(--gold);outline-offset:3px}.category-card:active,.leaf-card:active{transform:translateY(-1px) scale(.995)}
.option{transition:background .15s ease,border-color .15s ease,transform .1s ease}.option:active{transform:scale(.99)}.option.selected{border-color:var(--primary)!important;background:var(--primary-light)!important}
.ui-mock-layout{display:grid;grid-template-columns:minmax(0,1fr) 250px;gap:18px;align-items:start}.ui-question-panel{min-width:0}.ui-question-number{font-size:.82rem;font-weight:700;color:var(--primary-dark);margin-bottom:8px}.ui-question-panel .question-box{margin-bottom:0}.ui-palette{position:sticky;top:90px;background:linear-gradient(165deg,#fff,#f7fcf8 60%,#fffdf2);border:1px solid rgba(22,163,74,.14);border-radius:18px;padding:16px;box-shadow:var(--shadow);max-height:calc(100vh - 110px);overflow:auto}.ui-palette-title{font-family:Lexend,Inter,sans-serif;font-weight:700;color:var(--ink);margin-bottom:10px}.ui-palette-grid{display:grid;grid-template-columns:repeat(5,1fr);gap:7px}.ui-qnum{min-width:0;padding:8px 4px;border-radius:9px;border:1px solid var(--border);background:#fff;color:var(--text);font-weight:700;font-size:.8rem;cursor:pointer}.ui-qnum.current{background:var(--primary);border-color:var(--primary);color:#fff}.ui-qnum.answered{border-color:var(--gold-dark);box-shadow:inset 0 -3px 0 var(--gold)}.ui-qnum.reviewed{outline:2px solid rgba(22,163,74,.18)}.ui-mock-actions{display:flex;gap:10px;flex-wrap:wrap;margin-top:16px}.ui-mock-summary{display:grid;grid-template-columns:repeat(4,1fr);gap:12px}.ui-review-card{margin-top:12px}.ui-topic-row{display:grid;grid-template-columns:1fr auto;gap:10px;align-items:center;padding:9px 0;border-bottom:1px solid var(--border)}.ui-topic-bar{height:8px;border-radius:999px;background:#e9f0eb;overflow:hidden;margin-top:6px}.ui-topic-fill{height:100%;border-radius:999px;background:linear-gradient(90deg,var(--primary),var(--gold))}.ui-result-actions{display:flex;gap:10px;flex-wrap:wrap;margin-top:18px}
@media(max-width:820px){.ui-mock-layout{grid-template-columns:1fr}.ui-palette{position:static;max-height:none;order:-1}.ui-palette-grid{grid-template-columns:repeat(6,1fr)}}
@media(max-width:520px){.ui-palette-grid{grid-template-columns:repeat(5,1fr)}.ui-mock-summary{grid-template-columns:repeat(2,1fr)}}
#ui-toast-stack{position:fixed;left:50%;bottom:22px;transform:translateX(-50%);z-index:9999;display:flex;flex-direction:column;gap:8px;align-items:center}.ui-toast{min-width:180px;max-width:90vw;padding:12px 18px;border-radius:12px;background:#113c25;color:#fff;box-shadow:0 10px 24px rgba(16,56,35,.25);opacity:0;transform:translateY(10px);transition:opacity .2s ease,transform .2s ease}.ui-toast.show{opacity:1;transform:translateY(0)}.ui-toast.error{background:#b4233a}.ui-toast.success{background:#16814f}
#jeet-intro{position:fixed;inset:0;z-index:99999;display:grid;place-items:center;overflow:hidden;background:radial-gradient(circle at 50% 50%,rgba(242,201,76,.18),transparent 25%),linear-gradient(145deg,#04140b,#0a2f1c,#071b11);opacity:0;pointer-events:none;transition:opacity .2s ease}#jeet-intro.show{opacity:1;pointer-events:auto}.jeet-wrap{text-align:center}.jeet-name{font:800 clamp(2.3rem,10vw,6rem) Lexend,Inter,sans-serif;letter-spacing:.08em;text-transform:uppercase;color:#fff;text-shadow:0 0 28px rgba(34,197,94,.2)}.jeet-line{width:0;height:2px;margin:16px auto 0;background:linear-gradient(90deg,transparent,var(--gold),#fff,var(--gold),transparent);animation:jeetLine 1s ease .35s forwards}.jeet-sub{color:rgba(255,255,255,.65);letter-spacing:.35em;text-transform:uppercase;font-size:.75rem}@keyframes jeetLine{to{width:min(320px,60vw)}}
@media(prefers-reduced-motion:reduce){*{animation:none!important;transition:none!important}}
`;document.head.appendChild(s)}

function showJeetIntroOnce(){if(getPageName()!=="index.html")return;if(sessionStorage.getItem("exam-vault-jeet-intro-shown")==="1")return;sessionStorage.setItem("exam-vault-jeet-intro-shown","1");const o=document.createElement("div");o.id="jeet-intro";o.innerHTML='<div class="jeet-wrap"><div class="jeet-name">Jeet Mondal</div><div class="jeet-line"></div><div class="jeet-sub">Exam Vault</div></div>';document.body.appendChild(o);requestAnimationFrame(()=>o.classList.add("show"));setTimeout(()=>{o.classList.remove("show");setTimeout(()=>o.remove(),240)},1500)}
function showToast(msg,type=""){let stack=$("#ui-toast-stack");if(!stack){stack=document.createElement("div");stack.id="ui-toast-stack";document.body.appendChild(stack)}const t=document.createElement("div");t.className=`ui-toast${type?" "+type:""}`;t.textContent=msg;stack.appendChild(t);requestAnimationFrame(()=>t.classList.add("show"));setTimeout(()=>{t.classList.remove("show");setTimeout(()=>t.remove(),220)},2200)}
function skeletonCardsHTML(n=6){return `<section class="section"><div class="card-grid">${Array.from({length:n},()=>'<div class="card"><div class="icon">⏳</div><h3>Loading…</h3></div>').join("")}</div></section>`}
function skeletonBlockHTML(){return `<section class="section"><div class="notes-box"><p>Loading…</p></div></section>`}
async function loadJSON(path){try{const r=await fetch(path,{cache:"no-store"});if(!r.ok)return null;return await r.json()}catch(err){console.error("JSON load failed:",path,err);return null}}
async function loadText(path){try{const r=await fetch(path,{cache:"no-store"});return r.ok?await r.text():null}catch(err){console.error("Text load failed:",path,err);return null}}
function setAppHTML(html){const root=$("#app");if(!root)return;root.innerHTML=html;root.classList.remove("app-fade");requestAnimationFrame(()=>root.classList.add("app-fade-in"))}
function makeLink(page,params={}){const u=new URL(page,location.href);for(const[k,v]of Object.entries(params))if(v!==null&&v!==undefined&&v!=="")u.searchParams.set(k,v);return u.pathname.split("/").pop()+u.search}
function goTo(page,params={}){location.href=makeLink(page,params)}window.goTo=goTo;
function bindClickableCards(root=document){root.querySelectorAll('.category-card').forEach(c=>{const open=()=>goTo('study.html',{category:c.dataset.category,path:c.dataset.nextPath||''});c.onclick=open;c.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();open()}}});root.querySelectorAll('.leaf-card').forEach(c=>{const open=()=>goTo(c.dataset.page,{category:c.dataset.category,path:c.dataset.path||''});c.onclick=open;c.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();open()}}})}

async function renderHome(){setAppHTML(skeletonCardsHTML());const menu=await loadJSON(dataPath('menu.json'));if(!Array.isArray(menu)){setAppHTML('<div class="card"><h3>Menu not found</h3></div>');return}const cards=menu.map(i=>`<div class="card category-card" role="button" tabindex="0" data-category="${escapeHTML(i.folder||i.slug||'')}" aria-label="Open ${escapeHTML(i.name||i.title||'Item')}"><div class="icon">${escapeHTML(i.icon||'📁')}</div><h3>${escapeHTML(i.name||i.title||'Item')}</h3></div>`).join('');setAppHTML(`<section class="section"><h2 class="page-title">Select Category</h2><div class="card-grid">${cards}</div></section>`);bindClickableCards($('#app'))}

async function renderStudyPage(){const cat=APP.params.category||'';const seg=getCurrentPathSegments();if(!cat){await renderHome();return}setAppHTML(skeletonCardsHTML());const dir=currentDirPath(cat,seg);const items=await loadJSON(dataPath(cat,...seg,'items.json'));const defs=[{title:'Theory',icon:'📖',page:'notes.html',file:'notes.json'},{title:'MCQ Practice',icon:'📝',page:'mcq.html',file:'mcq.json'},{title:'Mock Test',icon:'🎯',page:'mock-test.html',file:'mock-test.json'}];const states=await Promise.all(defs.map(async d=>({...d,exists:!!(await loadJSON(dataPath(cat,...seg,d.file)))})));const child=Array.isArray(items)?items.map(i=>`<div class="card category-card" role="button" tabindex="0" data-category="${escapeHTML(cat)}" data-next-path="${escapeHTML(joinPath(seg,i.folder||i.slug||''))}"><div class="icon">${escapeHTML(i.icon||'📄')}</div><h3>${escapeHTML(itemLabel(i))}</h3></div>`).join(''):'';const leaves=states.filter(x=>x.exists).map(d=>`<div class="card leaf-card" role="button" tabindex="0" data-page="${d.page}" data-category="${escapeHTML(cat)}" data-path="${escapeHTML(joinPath(seg))}"><div class="icon">${d.icon}</div><h3>${d.title}</h3></div>`).join('');if(!child&&!leaves){setAppHTML(`<section class="section"><div class="page-nav"><button class="btn-back" onclick="history.back()">⬅ Back</button></div><h2 class="page-title">${escapeHTML(currentDirTitle(cat,seg))}</h2><p>No content found.</p><p>${escapeHTML(dir)}</p></section>`);return}setAppHTML(`<section class="section"><div class="page-nav"><button class="btn-back" onclick="history.back()">⬅ Back</button></div><h2 class="page-title">${escapeHTML(currentDirTitle(cat,seg))}</h2>${breadcrumbsHTML(cat,seg)}${child?`<div class="card-grid">${child}</div>`:''}${leaves?`<div class="card-grid mt-20">${leaves}</div>`:''}</section>`);bindClickableCards($('#app'))}

async function renderTheoryPage(){const cat=APP.params.category||'';const seg=getCurrentPathSegments();const path=dataPath(cat,...seg,'notes.json');setAppHTML(skeletonBlockHTML());const data=await loadJSON(path);if(!data){setAppHTML(`<div class="card"><h3>Theory not found</h3><p>${escapeHTML(path)}</p></div>`);return}const paras=String(data.content||'').split(/\n\n+/).map(p=>`<p>${escapeHTML(p).replaceAll('\n','<br>')}</p>`).join('');setAppHTML(`<section class="section"><div class="page-nav"><button class="btn-back" onclick="history.back()">⬅ Back</button></div><h2 class="page-title">${escapeHTML(data.title||'Theory')}</h2><div class="notes-box">${paras}</div></section>`)}

function formatTime(sec){sec=Math.max(0,Number(sec)||0);return `${String(Math.floor(sec/60)).padStart(2,'0')}:${String(sec%60).padStart(2,'0')}`}
function stopMockTimer(){if(APP.mock.timer){clearInterval(APP.mock.timer);APP.mock.timer=null}}
function scoreMock(data,selected){let correct=0,answered=0;for(let i=0;i<data.questions.length;i++){const a=selected[i];if(a!==undefined&&a!==null){answered++;if(Number(a)===Number(data.questions[i].answer))correct++}}return{correct,answered,wrong:answered-correct,unanswered:data.questions.length-answered,accuracy:data.questions.length?Math.round(correct/data.questions.length*100):0}}
function getMockTopicStats(data,selected){const map={};data.questions.forEach((q,i)=>{const topic=q.topic||'General';if(!map[topic])map[topic]={total:0,answered:0,correct:0,wrong:0};map[topic].total++;if(selected[i]!==undefined){map[topic].answered++;if(Number(selected[i])===Number(q.answer))map[topic].correct++;else map[topic].wrong++}});return Object.entries(map).map(([topic,v])=>({...v,topic,accuracy:v.total?Math.round(v.correct/v.total*100):0})).sort((a,b)=>a.accuracy-b.accuracy)}
function getMockReviewPath(q){return q.theoryPath||APP.params.path||''}
function renderMockQuestion(){const m=APP.mock,d=m.data,q=d.questions[m.index],total=d.questions.length,selected=m.selected[m.index];const options=q.options.map((o,i)=>`<button type="button" class="option ${selected===i?'selected':''}" data-opt="${i}">${String.fromCharCode(65+i)}) ${escapeHTML(o)}</button>`).join('');const nav=Array.from({length:total},(_,i)=>{const answered=m.selected[i]!==undefined;return `<button type="button" class="ui-qnum ${i===m.index?'current':''} ${answered?'answered':''}" data-q="${i}">${i+1}</button>`}).join('');setAppHTML(`<section class="section"><div class="page-nav"><button class="btn-back" onclick="history.back()">⬅ Back</button></div><div class="ui-mock-layout"><div class="ui-question-panel"><div class="timer" id="mock-timer">Time left: ${formatTime(m.timeLeft)}</div><div class="progress-wrap"><div class="progress-bar" style="width:${((m.index+1)/total)*100}%"></div></div><div class="question-box"><div class="ui-question-number">Question ${m.index+1} of ${total}</div><h3>${escapeHTML(q.question)}</h3><div class="option-list">${options}</div></div><div class="ui-mock-actions"><button class="btn btn-outline" id="prev-q" ${m.index===0?'disabled':''}>Previous</button>${m.index<total-1?'<button class="btn" id="next-q">Next</button>':'<button class="btn btn-success" id="submit-mock">Submit Test</button>'}</div></div><aside class="ui-palette"><div class="ui-palette-title">Questions</div><div class="ui-palette-grid">${nav}</div></aside></div></section>`);$('#prev-q')?.addEventListener('click',()=>{if(m.index>0){m.index--;renderMockQuestion()}});$('#next-q')?.addEventListener('click',()=>{if(m.index<total-1){m.index++;renderMockQuestion()}});$('#submit-mock')?.addEventListener('click',()=>finishMock(false));$$('.option').forEach(b=>b.addEventListener('click',()=>{m.selected[m.index]=Number(b.dataset.opt);renderMockQuestion()}));$$('[data-q]').forEach(b=>b.addEventListener('click',()=>{m.index=Number(b.dataset.q);renderMockQuestion()}))}
function reviewTheory(index){const q=APP.mock.data.questions[index];const path=getMockReviewPath(q);goTo('notes.html',{category:APP.params.category,path})}
function finishMock(auto=false){stopMockTimer();const m=APP.mock,d=m.data,s=scoreMock(d,m.selected),stats=getMockTopicStats(d,m.selected),wrong=d.questions.map((q,i)=>({q,i})).filter(x=>m.selected[x.i]!==undefined&&Number(m.selected[x.i])!==Number(x.q.answer));const answeredPct=d.questions.length?Math.round(s.answered/d.questions.length*100):0;const weak=stats.filter(x=>x.accuracy<70);const perfect=s.wrong===0&&s.unanswered===0;const wrongHtml=wrong.length?wrong.map(({q,i})=>`<div class="question-box ui-review-card"><h3>Q${q.id}. ${escapeHTML(q.question)}</h3><p>❌ Your answer: ${escapeHTML(q.options[m.selected[i]]??'Not answered')}</p><p>✅ Correct answer: ${escapeHTML(q.options[q.answer])}</p><p>📚 Topic: <b>${escapeHTML(q.topic||'General')}</b></p><button class="btn btn-outline" data-review="${i}">Review Theory</button></div>`).join(''):'<div class="card"><h3>🎉 Perfect! No wrong answers.</h3><p>Every answered question is correct.</p></div>';const topicHtml=stats.map(v=>`<div class="ui-topic-row"><div><b>${escapeHTML(v.topic)}</b><div class="ui-topic-bar"><div class="ui-topic-fill" style="width:${v.accuracy}%"></div></div></div><strong>${v.accuracy}%</strong></div>`).join('');setAppHTML(`<section class="section"><h2 class="page-title">Mock Test Result${auto?' — Time Up':''}</h2><div class="ui-mock-summary"><div class="card"><h3>Score</h3><p>${s.correct}/${d.questions.length}</p></div><div class="card"><h3>Accuracy</h3><p>${s.accuracy}%</p></div><div class="card"><h3>Wrong</h3><p>${s.wrong}</p></div><div class="card"><h3>Unanswered</h3><p>${s.unanswered}</p></div></div><div class="notes-box" style="margin-top:16px"><h3>Attempt Summary</h3><p>Answered: ${s.answered}/${d.questions.length} (${answeredPct}%)</p><p>Correct: ${s.correct} · Wrong: ${s.wrong} · Unanswered: ${s.unanswered}</p><h3>Weak Topics</h3>${stats.length?topicHtml:'<p>No topic data available.</p>'}${weak.length?`<p style="margin-top:12px"><b>Priority revision:</b> ${weak.slice(0,5).map(x=>escapeHTML(x.topic)).join(', ')}</p>`:''}</div><div class="section"><h3 class="page-title">Detailed Review</h3>${wrongHtml}</div><div class="ui-result-actions"><button class="btn" id="retry">Retry Test</button><button class="btn btn-outline" onclick="history.back()">Back</button></div>${perfect?'<div class="card" style="margin-top:16px"><h3>🏆 Excellent!</h3><p>You completed this mock test without mistakes.</p></div>':''}</section>`);$$('[data-review]').forEach(b=>b.addEventListener('click',()=>reviewTheory(Number(b.dataset.review))));$('#retry')?.addEventListener('click',()=>startMock())}
function startMock(){const d=APP.mock.data;if(!d||!Array.isArray(d.questions)||!d.questions.length){setAppHTML('<div class="card"><h3>Mock Test content not found.</h3></div>');return}stopMockTimer();APP.mock.index=0;APP.mock.selected={};APP.mock.timeLeft=Math.max(60,(Number(d.durationMinutes)||20)*60);APP.mock.startedAt=Date.now();APP.mock.timer=setInterval(()=>{APP.mock.timeLeft--;const el=$('#mock-timer');if(el)el.textContent=`Time left: ${formatTime(APP.mock.timeLeft)}`;if(APP.mock.timeLeft<=0){stopMockTimer();finishMock(true)}},1000);renderMockQuestion()}
async function renderMockPage(){const cat=APP.params.category||'';const seg=getCurrentPathSegments();const path=dataPath(cat,...seg,'mock-test.json');setAppHTML(skeletonBlockHTML());const data=await loadJSON(path);if(!data||!Array.isArray(data.questions)){setAppHTML(`<div class="card"><h3>Mock Test not found or invalid.</h3><p>${escapeHTML(path)}</p></div>`);return}APP.mock.data=data;setAppHTML(`<section class="section"><div class="page-nav"><button class="btn-back" onclick="history.back()">⬅ Back</button></div><h2 class="page-title">${escapeHTML(data.title||'Mock Test')}</h2><div class="ui-mock-summary"><div class="card"><h3>${data.questions.length}</h3><p>Questions</p></div><div class="card"><h3>${Number(data.durationMinutes)||20}</h3><p>Minutes</p></div></div><div class="notes-box" style="margin-top:16px"><p>Choose the best answer for each question. Use the question palette to jump between questions.</p></div><div class="ui-result-actions"><button class="btn btn-success" id="start-mock">Start Mock Test</button></div></section>`);$('#start-mock')?.addEventListener('click',startMock)}
function init(){injectUIStyles();APP.params=getParams();APP.currentPage=getPageName();if(APP.currentPage==='index.html'){showJeetIntroOnce();renderHome()}else if(APP.currentPage==='study.html')renderStudyPage();else if(APP.currentPage==='notes.html')renderTheoryPage();else if(APP.currentPage==='mock-test.html')renderMockPage();else renderHome()}
document.addEventListener('DOMContentLoaded',init);
